name: Testes Automatizados
on:
  push:
    branches:
      - main

jobs:
  test-soma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python.py
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install pytest

      - name: Testar soma
        run: pytest Python/tests/soma.py

  test-subtracao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python.py
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install pytest

      - name: Testar subtração
        run: pytest Python/tests/subtracao.py

  test-multiplicacao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python.py
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install pytest

      - name: Testar multiplicação
        run: pytest Python/tests/multiplicacao.py

  test-divisao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python.py
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install pytest

      - name: Testar divisão
        run: pytest Python/tests/divisao.py
